clink.argmatcher("my-app")
:addflags("-c")
:addflags("-v")
:addflags("-h")
:adddescriptions({"-h", description = "Print help"})
:addflags("--help")
:adddescriptions({"--help", description = "Print help"})
:addarg({ "test" .. clink.argmatcher()
    :addflags("-d")
    :addflags("-c")
    :addflags("-h")
    :adddescriptions({"-h", description = "Print help"})
    :addflags("--help")
    :adddescriptions({"--help", description = "Print help"})
})
:addarg({ "help" .. clink.argmatcher()
    :addarg({ "test" .. clink.argmatcher()
    })
    :addarg({ "help" .. clink.argmatcher()
    })
})
