.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app 3.0" 
.SH NAME
my/-app /- testing bash completions
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-f/fR|/fB/-/-flag/fR] [/fB/-o/fR|/fB/-/-option/fR] [/fB/-h/fR|/fB/-/-help/fR] [/fB/-V/fR|/fB/-/-version/fR] [/fIpositional/fR] 
.SH DESCRIPTION
testing bash completions
.SH OPTIONS
.TP
/fB/-f/fR, /fB/-/-flag/fR
cmd flag
.TP
/fB/-o/fR, /fB/-/-option/fR
cmd option
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help
.TP
/fB/-V/fR, /fB/-/-version/fR
Print version
.TP
[/fIpositional/fR]

.SH VERSION
v3.0
