.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my/-app
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-h/fR|/fB/-/-help/fR] [/fB/-c /fR] [/fB/-v /fR] [/fIsubcommands/fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help information
.TP
/fB/-c/fR

.TP
/fB/-v/fR

.SH SUBCOMMANDS
.TP
my/-app/-test(1)
Subcommand
.TP
my/-app/-help(1)
Print this message or the help of the given subcommand(s)
