.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my\-app
.SH SYNOPSIS
\fBmy\-app\fR [\fB\-0 \fR] [\fB\-a \fR] [\fB\-\-aa\fR] [\fB\-b \fR] [\fB\-c \fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-0\fR

.TP
\fB\-a\fR

.TP
\fB\-\-aa\fR

.TP
\fB\-b\fR

.TP
\fB\-c\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
