.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parent 1  "parent " 
.SH NAME
parent \- parent command
.SH SYNOPSIS
\fBparent\fR [\fB\-\-parent\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.br
\fBparent child1\fR [\fB\-\-child1\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.br
\fBparent child2\fR [\fB\-\-child2\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.br
\fBparent child3\fR [\fB\-\-child3\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.br
\fBparent help\fR 
.SH DESCRIPTION
parent command
.SH OPTIONS
.TP
\fB\-\-parent\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
\fBchild1\fR [\fB\-\-child1\fR] [\fB\-h\fR|\fB\-\-help\fR] 
child1 command
.TP
\fBchild2\fR [\fB\-\-child2\fR] [\fB\-h\fR|\fB\-\-help\fR] 
child2 command
.TP
\fBhelp\fR 
Print this message or the help of the given subcommand(s)
