.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my\-app
.SH SYNOPSIS
\fBmy\-app\fR [\fB\-r\fR|\fB\-\-recursive\fR] [\fB\-f\fR|\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIcolor\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-recursive\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH "CONFLICT OPTIONS"
.TP
\fB\-f\fR, \fB\-\-force\fR

.SH "GLOBAL OPTIONS"
.TP
[\fIcolor\fR]

.br
[\fIpossible values: \fRalways, never, auto]
