.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my\-app \- Check file types and compare values
.SH SYNOPSIS
\fBmy\-app\fR [OPTION]... EXPRESSION
.br
\fBmy\-app\fR
.br
[ EXPRESSION ]
.br
[ ]
.br
\&./my\-app EXPRESSION
.SH DESCRIPTION
Check file types and compare values
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-all\fR
Do not ignore entries starting with .
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
