.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my/-app
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-/-choice/fR] [/fB/-/-method/fR] [/fB/-h/fR|/fB/-/-help/fR] [/fIpositional_choice/fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
/fB/-/-choice/fR

.br
[/fIpossible values: /fRbash, fish, zsh]
.TP
/fB/-/-method/fR

.br
/fIPossible values:/fR
.RS 14
.IP /(bu 2
fast: use the Fast method
.IP /(bu 2
slow: use the slow method
.RE
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help (see a summary with /*(Aq/-h/*(Aq)
.TP
[/fIpositional_choice/fR]
Pick the Position you want the command to run in
.br

.br
/fIPossible values:/fR
.RS 14
.IP /(bu 2
left: run left adjusted
.IP /(bu 2
right
.RE
