.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my\-app \- Hello about!
.SH SYNOPSIS
\fBmy\-app\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIarg\fR] 
.SH DESCRIPTION
Hello about!
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIarg\fR]
Hello help!
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
fast
.IP \(bu 2
slow: Hello PossibleValue!
.RE
.SH EXTRA
Hello after_help!
