.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app 3.0" 
.SH NAME
my/-app /- Tests completions
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-c/fR|/fB/-/-config/fR]... [/fB/-h/fR|/fB/-/-help/fR] [/fB/-V/fR|/fB/-/-version/fR] [/fIfile/fR] [/fIchoice/fR] [/fIsubcommands/fR]
.SH DESCRIPTION
Tests completions
.SH OPTIONS
.TP
/fB/-c/fR, /fB/-/-config/fR
some config file
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help
.TP
/fB/-V/fR, /fB/-/-version/fR
Print version
.TP
[/fIfile/fR]
some input file
.TP
[/fIchoice/fR]

.br
[/fIpossible values: /fRfirst, second]
.SH SUBCOMMANDS
.TP
my/-app/-test(1)
tests things
.TP
my/-app/-some_cmd(1)
top level subcommand
.TP
my/-app/-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v3.0
