.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my/-app
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-/-choice/fR] [/fB/-/-unknown/fR] [/fB/-/-other/fR] [/fB/-p/fR|/fB/-/-path/fR] [/fB/-f/fR|/fB/-/-file/fR] [/fB/-d/fR|/fB/-/-dir/fR] [/fB/-e/fR|/fB/-/-exe/fR] [/fB/-/-cmd/-name/fR] [/fB/-c/fR|/fB/-/-cmd/fR] [/fB/-u/fR|/fB/-/-user/fR] [/fB/-H/fR|/fB/-/-host/fR] [/fB/-/-url/fR] [/fB/-/-email/fR] [/fB/-h/fR|/fB/-/-help/fR] [/fIcommand_with_args/fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
/fB/-/-choice/fR

.br
[/fIpossible values: /fRbash, fish, zsh]
.TP
/fB/-/-unknown/fR

.TP
/fB/-/-other/fR

.TP
/fB/-p/fR, /fB/-/-path/fR

.TP
/fB/-f/fR, /fB/-/-file/fR

.TP
/fB/-d/fR, /fB/-/-dir/fR

.TP
/fB/-e/fR, /fB/-/-exe/fR

.TP
/fB/-/-cmd/-name/fR

.TP
/fB/-c/fR, /fB/-/-cmd/fR

.TP
/fB/-u/fR, /fB/-/-user/fR

.TP
/fB/-H/fR, /fB/-/-host/fR

.TP
/fB/-/-url/fR

.TP
/fB/-/-email/fR

.TP
/fB/-h/fR, /fB/-/-help/fR
Print help
.TP
[/fIcommand_with_args/fR]

