.ie /n(.g .ds Aq /(aq
.el .ds Aq '
.TH my-app 1  "my-app " 
.SH NAME
my/-app
.SH SYNOPSIS
/fBmy/-app/fR [/fB/-c /fR] [/fB/-h/fR|/fB/-/-help/fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
/fB/-c/fR [default: config.toml]
Set configuration file path
.RS
May also be specified with the /fBCONFIG_FILE/fR environment variable. 
.RE
.TP
/fB/-h/fR, /fB/-/-help/fR
Print help (see a summary with /*(Aq/-h/*(Aq)
