name: pre-commit

permissions: {} # none

on:
  pull_request:
  push:
    branches: [master]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v7
    - uses: j178/prek-action@v3.0.0
||||||| 6d0d36b0
    - uses: actions/checkout@v6
    - uses: j178/prek-action@v1
=======
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
>>>>>>> _rust/main
      with:
        persist-credentials: false
    - name: prek
      uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
      with:
        prek-version: '0.5.0'
