name: rust-next

permissions:
  contents: read

on:
  schedule:
  - cron: '3 3 3 * *'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  CARGO_INCREMENTAL: 0

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      matrix:
        build: [stable, linux, windows, mac, nightly, minimal, default, next]
        include:
        - build: stable
          os: ubuntu-latest
          rust: "stable"
          features: "full"
        - build: linux
          os: ubuntu-latest
          rust: "beta"
          features: "full"
        - build: windows
          os: windows-latest
          rust: "beta"
          features: "full"
        - build: mac
          os: macos-latest
          rust: "beta"
          features: "full"
        - build: nightly
          os: ubuntu-latest
          rust: "nightly"
          features: "full"
        - build: minimal
          os: ubuntu-latest
          rust: "stable"
          features: "minimal"
        - build: default
          os: ubuntu-latest
          rust: "stable"
          features: "default"
        - build: next
          os: ubuntu-latest
          rust: "stable"
          features: "next"
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    env:
      # Reduce amount of data cached
      CARGO_PROFILE_DEV_DEBUG: line-tables-only
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - name: Initialize cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - name: Install shells
      if: runner.os == 'Linux'
      run: sudo apt-get install -y elvish fish zsh
    - name: Build
      run: make build-${{matrix.features}}
    - name: Test
      run: make test-${{matrix.features}}
    - name: Test (benches)
      run: make test-${{matrix.features}} ARGS='--workspace --benches'
    - name: Test (ultra-minimal)
      if: matrix.build == 'minimal'
      run: make test-minimal ARGS='--manifest-path Cargo.toml'
    - name: Test dynamic completions
      run: cargo test -p clap_complete -F unstable-dynamic
  latest:
    name: "Check latest dependencies"
    strategy:
      matrix:
        build: [stable]
        include:
        - build: stable
          os: ubuntu-latest
          rust: "stable"
          features: "full"
    runs-on: ${{ matrix.os }}
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      run: rustup update --no-self-update stable && rustup default stable
    - name: Initialize cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - name: Install cargo-hack
      uses: taiki-e/install-action@37f7c5781271959fb65b6b35224e28652ff2b63d  # v2.87.0
      with:
        tool: cargo-hack
    - name: Install shells
      if: runner.os == 'Linux'
      run: sudo apt-get install -y elvish fish zsh
    - name: Update dependencies
      run: cargo update
    - name: Build
      run: make build-${{matrix.features}}
    - name: Test
      run: make test-${{matrix.features}}
    - name: Test (benches)
      run: make test-${{matrix.features}} ARGS='--workspace --benches'
    - name: Test (ultra-minimal)
      if: matrix.build == 'minimal'
      run: make test-minimal ARGS='--manifest-path Cargo.toml'
    - name: Test dynamic completions
      run: cargo test -p clap_complete -F unstable-dynamic
