name: Site
on:
  push:
    branches: [master]
    paths: ["site/**"]
concurrency:
  group: site
jobs:
  site:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: site
          BUILD_ONLY: true
      - name: Deploy
        if: ${{ success() }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: site/public
